server:
  port: 0

spring:
  application:
    name: consumer

  cloud:
    stream:

      bindings:
        input:
          destination: test
          binder: kafka1
          contentType: application/json

      binders:
        kafka1:
          type: kafka
          environment:
            spring:
              kafka:
                brokers: localhost:9092

